### ISSUE TITLE
5.1.0在nextjs13中出现build error

### ISSUE THREAD

**Issue by tangzijun** [ant-design/ant-design-icons#572]
5.1.0在nextjs中出现build error，回退到5.0.1后可正常build。

```Type error: Property 'rev' is missing in type '{}' but required in type 'Pick<AntdIconProps, "onClick" | "onSelect" | "dir" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | ... 355 more ... | "twoToneColor">'.```

![image](https://github.com/ant-design/ant-design-icons/assets/11813048/8db084ae-fc7d-40e2-bfce-7050906201d4)

环境：
nextjs 13.4.2
@ant-design/icons 5.1.0

**Comment by ERuseckas** [comment]
getting same issue

**Comment by abearxiong** [comment]
+1. 寻常react项目打包也出错

**Comment by pavelprokes-avast** [comment]
+1

**Comment by EuphoriaCHN** [comment]
+1，demo：https://codesandbox.io/s/compassionate-monad-s8t9d6?file=/src/App.tsx

**Comment by afc163** [comment]
Upgrade `@types/react` and `@types/react-dom` version to latest https://codesandbox.io/s/blissful-elgamal-ljhtf1?file=/src/App.tsx

**Comment by Bosseskompis** [comment]
So react 17.x isn't supported then?

**Comment by Darcrandex** [comment]
+1

**Comment by michele-pinto-kensu** [comment]
+1

**Comment by xiaoqiang1999** [comment]
> Upgrade and version to latest https://codesandbox.io/s/blissful-elgamal-ljhtf1?file=/src/App.tsx`@types/react``@types/react-dom`

✔️The problem has been resolved. Thank you very much!

**Comment by z2015** [comment]
typescript upgrade to 5.x is also required.

**Comment by sonnh58** [comment]
+1

**Comment by dizefurkan** [comment]
I have already upgrade versions but still get error


Check out my comment for details; screenshots
https://github.com/ant-design/ant-design-icons/issues/483#issuecomment-1779061345
